name: CI - SecOps Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  security-checks:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: desafio01

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Configurar Poetry para criar .venv no projeto
        run: |
          poetry config virtualenvs.in-project true

      - name: Instalar dependências
        run: |
          poetry install --no-interaction --no-ansi

      - name: Rodar Ruff (lint)
        run: |
          poetry run ruff check .

      - name: Rodar Bandit (segurança)
        run: |
          poetry run bandit -r . -x .venv,__pycache__,tests,docs,dist,build

      - name: Rodar Safety (dependências)
        run: |
          poetry run safety check
